apiVersion: v2
description: A Helm chart for KubeRocketCI Portal
home: https://docs.kuberocketci.io/
name: krci-portal
type: application
version: 0.3.0
appVersion: 0.3.0
icon: https://docs.kuberocketci.io/img/logo.svg
keywords:
  - edp
  - kubernetes
  - kuberocketci
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/kuberocketci
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/KubeRocketCI/krci-portal
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: epamedp/krci-portal:0.3.0
      image: epamedp/krci-portal:0.3.0
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/links: |
    - name: KubeRocketCI Documentation
      url: https://docs.kuberocketci.io
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/kuberocketci
