{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageKRCIPortalSecrets }}
{{- $secretStore := include "krci-portal.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageKRCIPortalSecretsName }}
apiVersion: {{ include "app.externalSecrets.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: krci-portal-server-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: serverSecret
    remoteRef:
      key: {{ $awsSecretName }}
      property: krci-portal-server-secret.serverSecret
{{- end }}
