{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageKRCIPortalSecrets }}
{{- $secretStore := include "krci-portal.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageKRCIPortalSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: krci-portal
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: oidcClientSecret
    remoteRef:
      key: {{ $awsSecretName }}
      property: krci-portal.oidcClientSecret
{{- end }}
