{{- if .Values.eso.enabled }}
apiVersion: {{ include "app.externalSecrets.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: portal-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.eso.secretPath }}
        metadataPolicy: None
{{- end }}
