{{- if .Values.externalSecrets.enabled }}
{{- if eq .Values.externalSecrets.type "generic" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "krci-portal.secretStoreName" . }}-krci-portal
spec:
  provider:
    {{- with .Values.externalSecrets.secretProvider.generic.secretStore.providerConfig }}
      {{-  toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
