{{- if .Values.eso.enabled }}
{{- if eq .Values.eso.provider "generic" }}
apiVersion: {{ .Values.eso.apiVersion }}
kind: SecretStore
metadata:
  name: {{ .Release.Name }}
spec:
  provider:
    {{- with .Values.eso.generic.secretStore.providerConfig }}
      {{-  toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
