import { CODEBASE_FROM_TEMPLATE_FORM_NAMES } from "./names";
import { CodebaseCreationStrategy, Template, CodebaseType, CodebaseVersioning, CITool } from "@my-project/shared";
import { DialogProps } from "@/core/providers/Dialog/types";

export type CreateCodebaseFromTemplateDialogProps = DialogProps<{
  template: Template;
}>;

export type CreateCodebaseFromTemplateFormValues = {
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.NAME]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.DESCRIPTION]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.LANG]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.FRAMEWORK]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.BUILD_TOOL]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.STRATEGY]: CodebaseCreationStrategy;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.TYPE]: CodebaseType;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.VERSIONING_TYPE]: CodebaseVersioning;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.VERSIONING_START_FROM]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.CI_TOOL]: CITool;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.REPOSITORY_URL]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.GIT_SERVER]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.GIT_URL_PATH]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.DEFAULT_BRANCH]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.EMPTY_PROJECT]: boolean;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.PRIVATE]: boolean;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.VERSIONING_START_FROM_VERSION]: string;
  [CODEBASE_FROM_TEMPLATE_FORM_NAMES.VERSIONING_START_FROM_POSTFIX]: string;
};
